### PR TITLE
fast forward gshoz zip

### PR DESCRIPTION
**Pull request by IAHM-COL**
@helijah 

Dear Emmanuel

Richard Senior had made some improvements in this lovely plane. 
I wanted to ask you to consider merging these into the master branch of the plane

Best, 
Israel

### CODE REVIEW

**Comment by IAHM-COL** [comment]
@helijah 

To assist you in the evaluation of changes, keep in mind that these are the modified files

<pre><code>
    modified:   Models/Cockpit/Overhead/overhead.ac
    modified:   Models/Cockpit/Overhead/overhead.xml
    modified:   Models/Cockpit/Panel/Instruments/alt/alt.xml
    modified:   Models/Cockpit/Panel/Instruments/chronograph/chronograph.xml
    modified:   Models/Cockpit/Panel/Instruments/rmi/rmi.ac
    modified:   Models/Cockpit/Panel/Instruments/rmi/rmi.xml
    modified:   Models/Cockpit/Panel/Instruments/sperry/sperry.xml
    modified:   Models/Cockpit/Panel/Instruments/vor/vor.xml
    modified:   Models/Cockpit/Panel/panel.xml
    modified:   Models/Cockpit/cockpit.xml
    modified:   Nasal/dc3.nas
    modified:   Nasal/electrical.nas
    modified:   Nasal/fuel.nas
    modified:   Nasal/liveries.nas
    modified:   Nasal/views.xml
    modified:   dc-3-base.xml
    modified:   dc-3-yasim.xml
</code></pre>

And added:

<pre><code>
Models/Liveries/42100558-prop.png
    Models/Liveries/42100558.png
    Models/Liveries/42100558.xml
    Models/Liveries/BFL-prop.png
    Models/Liveries/BFL.png
    Models/Liveries/BFL.xml
    Models/Liveries/BUA-prop.png
    Models/Liveries/BUA.png
    Models/Liveries/BUA.xml
    Models/Liveries/C-FDBJ-prop.png
    Models/Liveries/C-FDBJ.png
    Models/Liveries/C-FDBJ.xml
    Models/Liveries/C-GWIR-propeller.png
    Models/Liveries/C-GWIR.png
    Models/Liveries/C-GWIR.xml
    Models/Liveries/CPC-prop.png
    Models/Liveries/CPC.png
    Models/Liveries/CPC.xml
    Models/Liveries/DAL-prop.png
    Models/Liveries/DAL.png
    Models/Liveries/DAL.xml
    Models/Liveries/DAN-propeller.png
    Models/Liveries/DAN.png
    Models/Liveries/DAN.xml
    Models/Liveries/DLH-prop.png
    Models/Liveries/DLH.png
    Models/Liveries/DLH.xml
    Models/Liveries/EIN-propeller.png
    Models/Liveries/EIN.png
    Models/Liveries/EIN.xml
    Models/Liveries/G-AGBD-propeller.png
    Models/Liveries/G-AGBD.png
    Models/Liveries/G-AGBD.xml
    Models/Liveries/G-AGHS-propeller.png
    Models/Liveries/G-AGHS.png
    Models/Liveries/G-AGHS.xml
    Models/Liveries/G-AMCA-AAG-prop.png
    Models/Liveries/G-AMFV-prop.png
    Models/Liveries/G-AMFV.png
    Models/Liveries/G-AMFV.xml
    Models/Liveries/G-AMFV_HD.png
    Models/Liveries/G-AMFV_HD.xml
    Models/Liveries/G-AMJU-propeller.png
    Models/Liveries/G-AMJU.png
    Models/Liveries/G-AMJU.xml
    Models/Liveries/G-AMKE-prop.png
    Models/Liveries/G-AMKE.png
    Models/Liveries/G-AMKE.xml
    Models/Liveries/G-AMKE_2048.png
    Models/Liveries/G-AMKE_2048.xml
    Models/Liveries/G-AMSV-AAG.png
    Models/Liveries/G-AMSV-AAG.xml
    Models/Liveries/HK-1315-propeller.png
    Models/Liveries/HK-1315.png
    Models/Liveries/HK-1315.xml
    Models/Liveries/JND-prop.png
    Models/Liveries/JND.png
    Models/Liveries/JND.xml
    Models/Liveries/KG496-propeller.png
    Models/Liveries/KG496.png
    Models/Liveries/KG496.xml
    Models/Liveries/N18949-propeller.png
    Models/Liveries/N18949.png
    Models/Liveries/N18949.xml
    Models/Liveries/N34PB-prop.png
    Models/Liveries/N34PB.png
    Models/Liveries/N34PB.xml
    Models/Liveries/OO-AUV.png
    Models/Liveries/OO-AUV.xml
    Models/Liveries/OZA-propeller.png
    Models/Liveries/OZA.png
    Models/Liveries/OZA.xml
    Models/Liveries/PAA-prop.png
    Models/Liveries/PAA.png
    Models/Liveries/PAA.xml
    Models/Liveries/PH-ALR-propeller.png
    Models/Liveries/PH-ALR.png
    Models/Liveries/PH-ALR.xml
    Models/Liveries/USAF-0-293727-high.png
    Models/Liveries/USAF-0-293727-high.xml
    Models/Liveries/USAF-0-293727.png
    Models/Liveries/USAF-0-293727.xml
    Models/Liveries/USAF-propeller.png
    Models/Liveries/USCG-12446-propeller.png
    Models/Liveries/USCG-12446.png
    Models/Liveries/USCG-12446.xml
    Models/Liveries/VH-ANH-propeller.png
    Models/Liveries/VH-ANH.png
    Models/Liveries/VH-ANH.xml
    Models/Liveries/ZA947-propeller.png
    Models/Liveries/ZA947.png
    Models/Liveries/ZA947.xml
    Tutorials/COPYING
    Tutorials/Dialogs/
    Tutorials/DualControl/
    Tutorials/Models/
    Tutorials/Nasal/
    Tutorials/Read-Me.txt
    Tutorials/Sounds/
    Tutorials/contributors.txt
    Tutorials/copilot-base.xml
    Tutorials/dc-3-base.xml
    Tutorials/dc-3-copilot-set.xml
    Tutorials/dc-3-copilot-yasim-cnf.xml
    Tutorials/dc-3-psg1-set.xml
    Tutorials/dc-3-psg2-set.xml
    Tutorials/dc-3-psg3-set.xml
    Tutorials/dc-3-psg4-set.xml
    Tutorials/dc-3-set.xml
    Tutorials/dc-3-splash.png
    Tutorials/dc-3-yasim-cnf.xml
    Tutorials/dc-3-yasim.xml
    Tutorials/dc-3-yasim_buck_flightnotes.txt
    Tutorials/dc-3A-set.xml
    Tutorials/dc-3A-yasim-cnf.xml
    Tutorials/dc-3A-yasim.xml
    Tutorials/mpmap_icon.png
    Tutorials/psg-base.xml
    Tutorials/thumbnail.jpg
</code></pre>

**Comment by helijah** [comment]
Click on "fast forward gshoz zip" make crashing my PC. So as I thought the utilsiation these html interfaces (heavy, poorly designed and without ergonomics) is not what it takes.

This is the last time I say it. Whether it gshoz file is sent directly to my email address if I would do anything!

**Comment by IAHM-COL** [comment]
ill send you the email

**Comment by pedromorgan** [comment]
Ok can I make some suggestions..

I'm about to update fgx, and want to make the zips downloadable etc..
https://github.com/fgx/fgx/tree/next

And there's a downlaoder in there..
And am packing my own aircraft as zips
http://downloads.freeflightsim.org/flightgear-aircraft/

So I want to use this project as a source (I give up with curt)..
So what we can have off github is the zip file,

But this means creating a "tag"

but can me number tag as either
1.2.3 = major.minor.patch
or
make it date
2015-12-24 < x mas present

Either way, the "tag" will create the zip file, which is what I want to download

Is there a new group ?
Can we use freeflightsim.org which Is a domain I have that needs using more please ??
http://api-docs.freeflightsim.org/
Adn a jenkisn server
http://jenkins.freeflightsim.org/

**Comment by IAHM-COL** [comment]
@helijah 

Good Morning Dear Emmanuel

I am sending you this email to facilitate your revision on changes made by Richard Senior on the Douglas-Dc3.
I found the aircraft to be one of the most heavy aircrafts in FG, and really slow to make initial launch. But it flies great. I think there is also some improvement in the taxiing behavior and some adjustments to the FDM.

The aircraft can be downloaded from 
https://github.com/FGMEMBERS/Douglas-Dc3/archive/gshoz.zip

After download rename the folder to Douglas-Dc3

I don't have a full record of changes, but this are listed in the git repository. Althought github webpage gets in trouble with the large diff, you can use your own local git software to find out this differences. I can provide you a text file with the diff as well if you find that convenient ;)

Thanks a lot for all your revisions,
Sincerely 

@IAHM-COL

**Comment by IAHM-COL** [comment]
@pedromorgan 

Dear Pete
I am not sure if I understand all your message above.
But in github you can make a zip from technically eveything.
Branches, Status of the repo on any given commit, HEADs, or tagged release.
Those zip files are great tool, for what you seem to intend with fgx, but they come with the prefix as you probably already are aware.

You can send me an email to discuss more about this, if you need some help for your fgx project

Sincerely
@IAHM-COL

**Pull request closed without merging**
